### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by gdkrmr** [jlmelville/sneer#2]
Seems to be due to numerical inaccuracy.

Produced by `R CMD check`

```
* checking tests ...
  Running ‘testthat.R’ [166s/166s]
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  > test_check("sneer")
  1. Failure: wSSNE gives different results to SSNE (@test_importance_weight.R#29) 
  min(knn_centrality) not equal to 62.02.
  1/1 mismatches
  [1] 62 - 62 == -0.02
```

**Comment by jlmelville** [comment]
I have turned down the tolerance on the importance-weighted SNE tests and the change is now committed to master.

Tests were already passing for me on Windows (10) or Linux (Antergos) with R 3.3.1, so I can't say for sure that there aren't further numerical problems lurking (there almost certainly are).

**Comment by gdkrmr** [comment]
just checked with latest master, no more errors

**Comment by jlmelville** [comment]
Great, thanks for checking! Closing.
